
<Serializable()> Public Class SpyRegX

    Public METAL As String = "Métal:"
    Public CRYSTAL As String = "Cristal:"
    Public DEUTERIUM As String = "Deutérium:"
    Public ENERGY As String = "Energie:"
    Public MISSILE_L As String = "Lanceur de missiles"
    Public SMALL_L As String = "Artillerie laser légère"
    Public HEAVY_L As String = "Artillerie laser lourde"
    Public ION_C As String = "Artillerie à ions"
    Public GAUSS_C As String = "Canon de Gauss"
    Public PLASMA_C As String = "Lanceur de plasma"
    Public SMALL_SD As String = "Petit bouclier"
    Public LARGE_SD As String = "Grand bouclier"
    Public SMALL_CS As String = "Petit transporteur"
    Public LARGE_CS As String = "Grand transporteur"
    Public INTERCEPT_M As String = "Missile Interception"
    Public INTERPLAN_M As String = "Missile Interplanétaire"
    Public LIGHT_F As String = "Chasseur léger"
    Public HEAVY_F As String = "Chasseur lourd"
    Public CRUISER As String = "Croiseur"
    Public BATTLE_S As String = "Vaisseau de bataille"
    Public ESPIONAGE_P As String = "Sonde espionnage"
    Public COLONY_SHIP As String = "Vaisseau de colonisation"
    Public RECYCLER As String = "Recycleur"
    Public BOMBER As String = "Bombardier"
    Public SOLAR_S As String = "Satellite solaire"
    Public DESTROYER As String = "Destructeur"
    Public TRAQUEUR As String = "Traqueur"
    Public DEATH_STAR As String = "Étoile de la mort"
    Public METAL_MINE As String = "Mine de métal"
    Public CRYSTAL_MINE As String = "Mine de cristal"
    Public DEUTERIUM_SYNTH As String = "Synthétiseur de deutérium"
    Public SOLAR_PLANT As String = "Centrale électrique solaire"
    Public FUSION_PLANT As String = "Centrale électrique de fusion"
    Public ROBOT_FACT As String = "Usine de robots"
    Public NANITE As String = "Usine de nanites"
    Public SHIPYARD As String = "Chantier spatial"
    Public METAL_STORAGE As String = "Hangar de métal"
    Public CRYSTAL_STORAGE As String = "Hangar de cristal"
    Public DEUTERIUM_TANK As String = "Réservoir de deutérium"
    Public RESEARCH_LAB As String = "Laboratoire de recherche"
    Public ROCKET_SILO As String = "Silo de missiles"
    Public LUNAR_B As String = "Base lunaire"
    Public PHALANGE As String = "Phalange de capteur"
    Public JUMPDOOR As String = "Porte de saut spatial"

    Public T_ESPIO As String = "Technologie Espionnage"
    Public T_COMPUTER As String = "Technologie Ordinateur"
    Public T_WEAPON As String = "Technologie Armes"
    Public T_SHIELD As String = "Technologie Bouclier"
    Public T_PROTECT As String = "Technologie Protection des vaisseaux spatiaux"
    Public T_ENERGY As String = "Technologie Energie"
    Public T_HYPER As String = "Technologie Hyperespace"
    Public T_COMBUS As String = "Réacteur à combustion"
    Public T_IMPULSE As String = "Réacteur à impulsion"
    Public T_PROPHYPER As String = "Propulsion hyperespace"
    Public T_LAZER As String = "Technologie Laser"
    Public T_IONS As String = "Technologie Ions"
    Public T_PLASMA As String = "Technologie Plasma"
    Public T_INTERNETWORK As String = "Réseau de recherche intergalactique"
    Public T_GRAVITON As String = "Technologie Graviton"
    Public SPYDESTROY As String = "Probabilité de destruction de la flotte d'espionnage :"
    Public Sub New()
        If OGameDBEngine.Default Is Nothing Then Return
        If OGameDBEngine.Default.Universe.template_lang <> "fr" Then
            ChangeLang(OGameDBEngine.Default.Universe.template_lang.ToLower)
        End If
    End Sub
    Protected Sub ChangeLang(ByVal lang As String)
        Select Case lang
            Case "org"
                METAL = "Metal:"
                CRYSTAL = "Crystal:"
                DEUTERIUM = "Deuterium:"
                ENERGY = "Energy:"
                MISSILE_L = "Rocket Launcher"
                SMALL_L = "Light Laser"
                HEAVY_L = "Heavy Laser"
                ION_C = "Ion Cannon"
                GAUSS_C = "Gauss Cannon"
                PLASMA_C = "Lanceur de plasma"
                SMALL_SD = "Small Shield Dome"
                LARGE_SD = "Large Shield Dome"
                SMALL_CS = "Small Cargo"
                LARGE_CS = "Large Cargo"
                INTERCEPT_M = "Anti-Ballistic Missiles"
                INTERPLAN_M = "Missile Interplanétaire"
                LIGHT_F = "Light Fighter"
                HEAVY_F = "Heavy Fighter"
                CRUISER = "Cruiser"
                BATTLE_S = "Battleship"
                ESPIONAGE_P = "Espionage Probe"
                COLONY_SHIP = "Colony Ship"
                RECYCLER = "Recycler"
                BOMBER = "Bomber"
                SOLAR_S = "Solar Satellite"
                DESTROYER = "Destroyer"
                DESTROYER = "Traqueur"
                DEATH_STAR = "Étoile de la mort"
                METAL_MINE = "Metal Mine"
                CRYSTAL_MINE = "Crystal Mine"
                DEUTERIUM_SYNTH = "Deuterium Synthesizer"
                SOLAR_PLANT = "Solar Plant"
                FUSION_PLANT = "Fusion Reactor"
                ROBOT_FACT = "Robotics Factory"
                NANITE = "Nanite Factory"
                SHIPYARD = "Shipyard"
                METAL_STORAGE = "Metal Storage"
                CRYSTAL_STORAGE = "Crystal Storage"
                DEUTERIUM_TANK = "Deuterium Tank"
                RESEARCH_LAB = "Research Lab"
                ROCKET_SILO = "Missile Silo"
                LUNAR_B = "Lunar Base"
                PHALANGE = "Sensor Phalanx"
                JUMPDOOR = "Jump Gate"

                T_ESPIO = "Espionage Technology"
                T_COMPUTER = "Computer Technology"
                T_WEAPON = "Weapons Technology"
                T_SHIELD = "Shielding Technology"
                T_PROTECT = "Armour Technology"
                T_ENERGY = "Energy Technology"
                T_HYPER = "Hyperspace Technology"
                T_COMBUS = "Combustion Drive"
                T_IMPULSE = "Impulse Drive"
                T_PROPHYPER = "Hyperspace Drive"
                T_LAZER = "Laser Technology"
                T_IONS = "Ion Technology"
                T_PLASMA = "Plasma Technology"
                T_INTERNETWORK = "Intergalactic Research Network"
                T_GRAVITON = "Graviton Technology"
                SPYDESTROY = "Chance of counter-espionage:"
        End Select
    End Sub
End Class