CREATE TABLE "PLAYERS" (
	"ID" INTEGER NOT NULL PRIMARY KEY ,
	"NAME" VARCHAR(30) NOT NULL ,
	"ALLIANCE" VARCHAR(30) ,
	"MAINPLANETCOORDS" VARCHAR(8),
	"DATASENDER" VARCHAR(16) ,
	"DATADATE" TIMESTAMP NOT NULL 
);

CREATE GENERATOR "PLAYER_ID";
CREATE INDEX PLAYERS_IDX1 ON PLAYERS (NAME, ALLIANCE);

SET TERM^;

CREATE TRIGGER "TRIGGER_PLAYER_ID" FOR PLAYERS
BEFORE INSERT POSITION 0
AS
BEGIN
	IF (NEW.ID IS NULL) THEN
		NEW.ID = GEN_ID("PLAYER_ID",1);
END^

SET TERM;^

CREATE TABLE "PLAYERSRANK" (
	"ID" INTEGER NOT NULL PRIMARY KEY,
	"PLAYER_ID" INTEGER NOT NULL,
	"RANK" INTEGER NOT NULL ,
	"POINTS" INTEGER NOT NULL,
	"DATASENDER" VARCHAR(16) ,
	"DATADATE" TIMESTAMP NOT NULL 
);

CREATE GENERATOR  "PLAYERRANK_ID";

SET TERM^;

CREATE TRIGGER "TRIGGER_PLAYERRANK_ID" FOR "PLAYERSRANK"
BEFORE INSERT POSITION 0
AS
BEGIN
	IF (NEW.ID IS NULL) THEN
		NEW.ID = GEN_ID("PLAYERRANK_ID",1);
END^
SET TERM;^



CREATE TABLE PLAYERSFLOTTE (
	"ID" INTEGER NOT NULL PRIMARY KEY ,
	"PLAYER_ID" INTEGER NOT NULL ,
	"RANK" INTEGER NOT NULL ,
	"POINTS" INTEGER ,
	"DATASENDER" VARCHAR(16) ,
	"DATADATE" TIMESTAMP NOT NULL 
 
);

CREATE GENERATOR  "PLAYERFLOTTE_ID";

SET TERM^;

CREATE TRIGGER "TRIGGER_PLAYERFLOTTE_ID" FOR "PLAYERSFLOTTE"
BEFORE INSERT POSITION 0
AS
BEGIN
	IF (NEW.ID IS NULL) THEN
		NEW.ID = GEN_ID("PLAYERFLOTTE_ID",1);
	
END^
SET TERM;^




CREATE TABLE PLAYERSRESEARCH (
	"ID" INTEGER NOT NULL PRIMARY KEY ,
	"PLAYER_ID" INTEGER NOT NULL ,
	"RANK" INTEGER NOT NULL ,
	"POINTS" INTEGER ,
	"DATASENDER" VARCHAR(16) ,
	"DATADATE" TIMESTAMP NOT NULL 
);

CREATE GENERATOR  "PLAYERSRESEARCH_ID";

SET TERM^;

CREATE TRIGGER "TRIGGER_PLAYERRESEARCH_ID" FOR "PLAYERSRESEARCH"
BEFORE INSERT POSITION 0
AS
BEGIN
	IF (NEW.ID IS NULL) THEN
		NEW.ID = GEN_ID("PLAYERSRESEARCH_ID",1);
	
END^

SET TERM;^


CREATE TABLE PLANETS (
	"ID" INTEGER NOT NULL PRIMARY KEY ,
	"NAME" VARCHAR(30) NOT NULL,
	"GALAXY" INTEGER,
	"SYSTEM" INTEGER,
	"PLANETNUM" INTEGER,
	"MOON" VARCHAR(20) NOT NULL ,
	"FIELDS" VARCHAR(30) NOT NULL,
	"PLAYERID" INTEGER,
	"DATASENDER" VARCHAR(16) ,
	"DATADATE" TIMESTAMP NOT NULL 
);
ALTER TABLE PLANETS
ADD COORDS COMPUTED BY (('[' || GALAXY || ':' || SYSTEM || ':' || PLANETNUM || ']'));

CREATE GENERATOR  "PLANETS_ID";

SET TERM^;

CREATE TRIGGER "TRIGGER_PLANETS_ID" FOR "PLANETS"
BEFORE INSERT POSITION 0
AS
BEGIN
	IF (NEW.ID IS NULL) THEN
		NEW.ID = GEN_ID("PLANETS_ID",1);
END^

SET TERM;^


CREATE TABLE ESPIONAGES (
	"ID" INTEGER NOT NULL PRIMARY KEY ,
	"PLANET_ID" INTEGER NOT NULL,
	"DATA" BLOB SUB_TYPE TEXT,
	"DATASENDER" VARCHAR(16) ,
	"DATADATE" TIMESTAMP NOT NULL 
);

CREATE GENERATOR  "ESPIONAGES_ID";

SET TERM^;

CREATE TRIGGER "TRIGGER_ESPIONAGES_ID" FOR "ESPIONAGES"
BEFORE INSERT POSITION 0
AS
BEGIN
	IF (NEW.ID IS NULL) THEN
		NEW.ID = GEN_ID("ESPIONAGES_ID",1);
END^

SET TERM;^

CREATE TABLE COMBATS (
	"ID" INTEGER NOT NULL PRIMARY KEY ,
	"ATTACKER_ID" INTEGER NOT NULL,
	"DEFENDER_ID" INTEGER NOT NULL,
	"ATTACKER_PLANET" VARCHAR(8),
	"DEFENDER_PLANET" VARCHAR(8),
	"DATA" BLOB SUB_TYPE TEXT,
	"DATASENDER" VARCHAR(16) ,
	"DATADATE" TIMESTAMP NOT NULL 
);

CREATE GENERATOR  "COMBATS_ID";

SET TERM^;

CREATE TRIGGER "TRIGGER_COMBATS_ID" FOR "COMBATS"
BEFORE INSERT POSITION 0
AS
BEGIN
	IF (NEW.ID IS NULL) THEN
		NEW.ID = GEN_ID("COMBATS_ID",1);
END^

SET TERM;^

CREATE VIEW RANKINGPOINTS(
    PLAYER_ID,
    "Rank",
    "Name",
    "Alliance",
    "Points",
    DATADATE,
    "DATASENDER")
AS
select DISTINCT P.ID,PR.RANK,P.NAME ,P.ALLIANCE,PR.POINTS,PR.DATADATE,PR.DATASENDER  from PLAYERS P, PLAYERSRANK PR
where PR.player_id = P.ID
and PR.DATADATE = (SELECT MAX(DATADATE) FROM playersrank WHERE PLAYER_ID=PR.player_id )
;

CREATE VIEW RANKINGFLOTTE(
    PLAYER_ID,
    "Rank",
    "Name",
    "Alliance",
    "Points",
    DATADATE,
    "DATASENDER")
AS
select DISTINCT P.ID,PR.RANK,P.NAME ,P.ALLIANCE,PR.POINTS,PR.DATADATE ,PR.DATASENDER from PLAYERS P, PLAYERSFLOTTE PR
where (PR.player_id = P.ID
and PR.DATADATE = (SELECT MAX(DATADATE) FROM playersflotte WHERE PLAYER_ID=PR.player_id ))
;

CREATE VIEW RANKINGRESEARCH(
    PLAYER_ID,
    "Rank",
    "Name",
    "Alliance",
    "Points",
    DATADATE,
    "DATASENDER")
AS
select DISTINCT P.ID,PR.RANK,P.NAME ,P.ALLIANCE,PR.POINTS,PR.DATADATE,PR.DATASENDER  from PLAYERS P, playersresearch  PR
where (PR.player_id = P.ID
and PR.DATADATE = (SELECT MAX(DATADATE) FROM playersresearch  WHERE PLAYER_ID=PR.player_id ))
;

CREATE VIEW ESPIONAGESREPORT(
    NAME,
    COORDS,
    RAWREPORT,
    DATADATE,
    DATASENDER)
AS
select P.name , P.coords  ,E.data ,E.datadate ,E.datasender  from planets P, espionages E
where P.id = E.planet_id
;