# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_simulatorWidget.ui'
#
# Created: Fri Feb  1 16:13:26 2008
#      by: PyQt4 UI code generator 4.3.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_simulatorWidget(object):
    def setupUi(self, simulatorWidget):
        simulatorWidget.setObjectName("simulatorWidget")
        simulatorWidget.resize(QtCore.QSize(QtCore.QRect(0,0,801,547).size()).expandedTo(simulatorWidget.minimumSizeHint()))

        self.groupBoxFlotte = QtGui.QGroupBox(simulatorWidget)
        self.groupBoxFlotte.setGeometry(QtCore.QRect(4,4,333,329))
        self.groupBoxFlotte.setCheckable(False)
        self.groupBoxFlotte.setObjectName("groupBoxFlotte")

        self.dCle = QtGui.QLineEdit(self.groupBoxFlotte)
        self.dCle.setGeometry(QtCore.QRect(60,84,60,18))
        self.dCle.setAlignment(QtCore.Qt.AlignRight)
        self.dCle.setObjectName("dCle")

        self.lRe = QtGui.QLabel(self.groupBoxFlotte)
        self.lRe.setGeometry(QtCore.QRect(4,184,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lRe.setFont(font)
        self.lRe.setWordWrap(False)
        self.lRe.setObjectName("lRe")

        self.lDe = QtGui.QLabel(self.groupBoxFlotte)
        self.lDe.setGeometry(QtCore.QRect(4,264,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lDe.setFont(font)
        self.lDe.setWordWrap(False)
        self.lDe.setObjectName("lDe")

        self.ldEm = QtGui.QLabel(self.groupBoxFlotte)
        self.ldEm.setGeometry(QtCore.QRect(120,284,72,18))
        self.ldEm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldEm.setWordWrap(False)
        self.ldEm.setObjectName("ldEm")

        self.ldCle = QtGui.QLabel(self.groupBoxFlotte)
        self.ldCle.setGeometry(QtCore.QRect(120,84,72,18))
        self.ldCle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldCle.setWordWrap(False)
        self.ldCle.setObjectName("ldCle")

        self.lSs = QtGui.QLabel(self.groupBoxFlotte)
        self.lSs.setGeometry(QtCore.QRect(4,244,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lSs.setFont(font)
        self.lSs.setWordWrap(False)
        self.lSs.setObjectName("lSs")

        self.laBo = QtGui.QLabel(self.groupBoxFlotte)
        self.laBo.setGeometry(QtCore.QRect(256,224,72,18))
        self.laBo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.laBo.setWordWrap(False)
        self.laBo.setObjectName("laBo")

        self.ldGt = QtGui.QLabel(self.groupBoxFlotte)
        self.ldGt.setGeometry(QtCore.QRect(120,64,72,18))
        self.ldGt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldGt.setWordWrap(False)
        self.ldGt.setObjectName("ldGt")

        self.aClo = QtGui.QLineEdit(self.groupBoxFlotte)
        self.aClo.setGeometry(QtCore.QRect(196,104,60,18))
        self.aClo.setAlignment(QtCore.Qt.AlignRight)
        self.aClo.setObjectName("aClo")

        self.ldSe = QtGui.QLabel(self.groupBoxFlotte)
        self.ldSe.setGeometry(QtCore.QRect(120,204,72,18))
        self.ldSe.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldSe.setWordWrap(False)
        self.ldSe.setObjectName("ldSe")

        self.aVc = QtGui.QLineEdit(self.groupBoxFlotte)
        self.aVc.setGeometry(QtCore.QRect(196,164,60,18))
        self.aVc.setAlignment(QtCore.Qt.AlignRight)
        self.aVc.setObjectName("aVc")

        self.dClo = QtGui.QLineEdit(self.groupBoxFlotte)
        self.dClo.setGeometry(QtCore.QRect(60,104,60,18))
        self.dClo.setAlignment(QtCore.Qt.AlignRight)
        self.dClo.setObjectName("dClo")

        self.ldSs = QtGui.QLabel(self.groupBoxFlotte)
        self.ldSs.setGeometry(QtCore.QRect(120,244,72,18))
        self.ldSs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldSs.setWordWrap(False)
        self.ldSs.setObjectName("ldSs")

        self.aRe = QtGui.QLineEdit(self.groupBoxFlotte)
        self.aRe.setGeometry(QtCore.QRect(196,184,60,18))
        self.aRe.setAlignment(QtCore.Qt.AlignRight)
        self.aRe.setObjectName("aRe")

        self.resetDef = QtGui.QPushButton(self.groupBoxFlotte)
        self.resetDef.setGeometry(QtCore.QRect(116,24,20,18))
        self.resetDef.setFocusPolicy(QtCore.Qt.NoFocus)
        self.resetDef.setObjectName("resetDef")

        self.laRe = QtGui.QLabel(self.groupBoxFlotte)
        self.laRe.setGeometry(QtCore.QRect(256,184,72,18))
        self.laRe.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.laRe.setWordWrap(False)
        self.laRe.setObjectName("laRe")

        self.lClo = QtGui.QLabel(self.groupBoxFlotte)
        self.lClo.setGeometry(QtCore.QRect(4,104,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lClo.setFont(font)
        self.lClo.setWordWrap(False)
        self.lClo.setObjectName("lClo")

        self.lCr = QtGui.QLabel(self.groupBoxFlotte)
        self.lCr.setGeometry(QtCore.QRect(4,124,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lCr.setFont(font)
        self.lCr.setWordWrap(False)
        self.lCr.setObjectName("lCr")

        self.laDe = QtGui.QLabel(self.groupBoxFlotte)
        self.laDe.setGeometry(QtCore.QRect(256,264,72,18))
        self.laDe.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.laDe.setWordWrap(False)
        self.laDe.setObjectName("laDe")

        self.lBo = QtGui.QLabel(self.groupBoxFlotte)
        self.lBo.setGeometry(QtCore.QRect(4,224,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lBo.setFont(font)
        self.lBo.setWordWrap(False)
        self.lBo.setObjectName("lBo")

        self.lSe = QtGui.QLabel(self.groupBoxFlotte)
        self.lSe.setGeometry(QtCore.QRect(4,204,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lSe.setFont(font)
        self.lSe.setWordWrap(False)
        self.lSe.setObjectName("lSe")

        self.ldVb = QtGui.QLabel(self.groupBoxFlotte)
        self.ldVb.setGeometry(QtCore.QRect(120,144,72,18))
        self.ldVb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldVb.setWordWrap(False)
        self.ldVb.setObjectName("ldVb")

        self.dVb = QtGui.QLineEdit(self.groupBoxFlotte)
        self.dVb.setGeometry(QtCore.QRect(60,144,60,18))
        self.dVb.setAlignment(QtCore.Qt.AlignRight)
        self.dVb.setObjectName("dVb")

        self.laVb = QtGui.QLabel(self.groupBoxFlotte)
        self.laVb.setGeometry(QtCore.QRect(256,144,72,18))
        self.laVb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.laVb.setWordWrap(False)
        self.laVb.setObjectName("laVb")

        self.laClo = QtGui.QLabel(self.groupBoxFlotte)
        self.laClo.setGeometry(QtCore.QRect(256,104,72,18))
        self.laClo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.laClo.setWordWrap(False)
        self.laClo.setObjectName("laClo")

        self.lVb = QtGui.QLabel(self.groupBoxFlotte)
        self.lVb.setGeometry(QtCore.QRect(4,144,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lVb.setFont(font)
        self.lVb.setWordWrap(False)
        self.lVb.setObjectName("lVb")

        self.aSe = QtGui.QLineEdit(self.groupBoxFlotte)
        self.aSe.setGeometry(QtCore.QRect(196,204,60,18))
        self.aSe.setAlignment(QtCore.Qt.AlignRight)
        self.aSe.setObjectName("aSe")

        self.ldVc = QtGui.QLabel(self.groupBoxFlotte)
        self.ldVc.setGeometry(QtCore.QRect(120,164,72,18))
        self.ldVc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldVc.setWordWrap(False)
        self.ldVc.setObjectName("ldVc")

        self.dCro = QtGui.QLineEdit(self.groupBoxFlotte)
        self.dCro.setGeometry(QtCore.QRect(60,124,60,18))
        self.dCro.setAlignment(QtCore.Qt.AlignRight)
        self.dCro.setObjectName("dCro")

        self.lVc = QtGui.QLabel(self.groupBoxFlotte)
        self.lVc.setGeometry(QtCore.QRect(4,164,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lVc.setFont(font)
        self.lVc.setWordWrap(False)
        self.lVc.setObjectName("lVc")

        self.ldBo = QtGui.QLabel(self.groupBoxFlotte)
        self.ldBo.setGeometry(QtCore.QRect(120,224,72,18))
        self.ldBo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldBo.setWordWrap(False)
        self.ldBo.setObjectName("ldBo")

        self.lCle = QtGui.QLabel(self.groupBoxFlotte)
        self.lCle.setGeometry(QtCore.QRect(4,84,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lCle.setFont(font)
        self.lCle.setWordWrap(False)
        self.lCle.setObjectName("lCle")

        self.laPt = QtGui.QLabel(self.groupBoxFlotte)
        self.laPt.setGeometry(QtCore.QRect(256,44,72,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.laPt.setFont(font)
        self.laPt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.laPt.setWordWrap(False)
        self.laPt.setObjectName("laPt")

        self.dVc = QtGui.QLineEdit(self.groupBoxFlotte)
        self.dVc.setGeometry(QtCore.QRect(60,164,60,18))
        self.dVc.setAlignment(QtCore.Qt.AlignRight)
        self.dVc.setObjectName("dVc")

        self.lGt = QtGui.QLabel(self.groupBoxFlotte)
        self.lGt.setGeometry(QtCore.QRect(4,64,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lGt.setFont(font)
        self.lGt.setWordWrap(False)
        self.lGt.setObjectName("lGt")

        self.ldDe = QtGui.QLabel(self.groupBoxFlotte)
        self.ldDe.setGeometry(QtCore.QRect(120,264,72,18))
        self.ldDe.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldDe.setWordWrap(False)
        self.ldDe.setObjectName("ldDe")

        self.ldRe = QtGui.QLabel(self.groupBoxFlotte)
        self.ldRe.setGeometry(QtCore.QRect(120,184,72,18))
        self.ldRe.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldRe.setWordWrap(False)
        self.ldRe.setObjectName("ldRe")

        self.ldPt = QtGui.QLabel(self.groupBoxFlotte)
        self.ldPt.setGeometry(QtCore.QRect(120,44,72,18))
        self.ldPt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldPt.setWordWrap(False)
        self.ldPt.setObjectName("ldPt")

        self.aCro = QtGui.QLineEdit(self.groupBoxFlotte)
        self.aCro.setGeometry(QtCore.QRect(196,124,60,18))
        self.aCro.setAlignment(QtCore.Qt.AlignRight)
        self.aCro.setObjectName("aCro")

        self.aVb = QtGui.QLineEdit(self.groupBoxFlotte)
        self.aVb.setGeometry(QtCore.QRect(196,144,60,18))
        self.aVb.setAlignment(QtCore.Qt.AlignRight)
        self.aVb.setObjectName("aVb")

        self.ldTr = QtGui.QLabel(self.groupBoxFlotte)
        self.ldTr.setGeometry(QtCore.QRect(120,304,72,18))
        self.ldTr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldTr.setWordWrap(False)
        self.ldTr.setObjectName("ldTr")

        self.laEm = QtGui.QLabel(self.groupBoxFlotte)
        self.laEm.setGeometry(QtCore.QRect(256,284,72,18))
        self.laEm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.laEm.setWordWrap(False)
        self.laEm.setObjectName("laEm")

        self.laTr = QtGui.QLabel(self.groupBoxFlotte)
        self.laTr.setGeometry(QtCore.QRect(256,304,72,18))
        self.laTr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.laTr.setWordWrap(False)
        self.laTr.setObjectName("laTr")

        self.aBo = QtGui.QLineEdit(self.groupBoxFlotte)
        self.aBo.setGeometry(QtCore.QRect(196,224,60,18))
        self.aBo.setAlignment(QtCore.Qt.AlignRight)
        self.aBo.setObjectName("aBo")

        self.aGt = QtGui.QLineEdit(self.groupBoxFlotte)
        self.aGt.setGeometry(QtCore.QRect(196,64,60,18))
        self.aGt.setAlignment(QtCore.Qt.AlignRight)
        self.aGt.setObjectName("aGt")

        self.resetAtt = QtGui.QPushButton(self.groupBoxFlotte)
        self.resetAtt.setGeometry(QtCore.QRect(176,24,20,18))
        self.resetAtt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.resetAtt.setObjectName("resetAtt")

        self.dGt = QtGui.QLineEdit(self.groupBoxFlotte)
        self.dGt.setGeometry(QtCore.QRect(60,64,60,18))
        self.dGt.setAlignment(QtCore.Qt.AlignRight)
        self.dGt.setObjectName("dGt")

        self.laCle = QtGui.QLabel(self.groupBoxFlotte)
        self.laCle.setGeometry(QtCore.QRect(256,84,72,18))
        self.laCle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.laCle.setWordWrap(False)
        self.laCle.setObjectName("laCle")

        self.ldClo = QtGui.QLabel(self.groupBoxFlotte)
        self.ldClo.setGeometry(QtCore.QRect(120,104,72,18))
        self.ldClo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldClo.setWordWrap(False)
        self.ldClo.setObjectName("ldClo")

        self.laCr = QtGui.QLabel(self.groupBoxFlotte)
        self.laCr.setGeometry(QtCore.QRect(256,124,72,18))
        self.laCr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.laCr.setWordWrap(False)
        self.laCr.setObjectName("laCr")

        self.laGt = QtGui.QLabel(self.groupBoxFlotte)
        self.laGt.setGeometry(QtCore.QRect(256,64,72,18))
        self.laGt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.laGt.setWordWrap(False)
        self.laGt.setObjectName("laGt")

        self.laSe = QtGui.QLabel(self.groupBoxFlotte)
        self.laSe.setGeometry(QtCore.QRect(256,204,72,18))
        self.laSe.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.laSe.setWordWrap(False)
        self.laSe.setObjectName("laSe")

        self.ldCr = QtGui.QLabel(self.groupBoxFlotte)
        self.ldCr.setGeometry(QtCore.QRect(120,124,72,18))
        self.ldCr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldCr.setWordWrap(False)
        self.ldCr.setObjectName("ldCr")

        self.laVc = QtGui.QLabel(self.groupBoxFlotte)
        self.laVc.setGeometry(QtCore.QRect(256,164,72,18))
        self.laVc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.laVc.setWordWrap(False)
        self.laVc.setObjectName("laVc")

        self.dPt = QtGui.QLineEdit(self.groupBoxFlotte)
        self.dPt.setGeometry(QtCore.QRect(60,44,60,18))
        self.dPt.setAlignment(QtCore.Qt.AlignRight)
        self.dPt.setObjectName("dPt")

        self.dRe = QtGui.QLineEdit(self.groupBoxFlotte)
        self.dRe.setGeometry(QtCore.QRect(60,184,60,18))
        self.dRe.setAlignment(QtCore.Qt.AlignRight)
        self.dRe.setObjectName("dRe")

        self.aPt = QtGui.QLineEdit(self.groupBoxFlotte)
        self.aPt.setGeometry(QtCore.QRect(196,44,60,18))
        self.aPt.setAlignment(QtCore.Qt.AlignRight)
        self.aPt.setObjectName("aPt")

        self.aCle = QtGui.QLineEdit(self.groupBoxFlotte)
        self.aCle.setGeometry(QtCore.QRect(196,84,60,18))
        self.aCle.setAlignment(QtCore.Qt.AlignRight)
        self.aCle.setObjectName("aCle")

        self.dEm = QtGui.QLineEdit(self.groupBoxFlotte)
        self.dEm.setGeometry(QtCore.QRect(60,284,60,18))
        self.dEm.setAlignment(QtCore.Qt.AlignRight)
        self.dEm.setObjectName("dEm")

        self.dDe = QtGui.QLineEdit(self.groupBoxFlotte)
        self.dDe.setGeometry(QtCore.QRect(60,264,60,18))
        self.dDe.setAlignment(QtCore.Qt.AlignRight)
        self.dDe.setObjectName("dDe")

        self.dSs = QtGui.QLineEdit(self.groupBoxFlotte)
        self.dSs.setGeometry(QtCore.QRect(60,244,60,18))
        self.dSs.setAlignment(QtCore.Qt.AlignRight)
        self.dSs.setObjectName("dSs")

        self.dBo = QtGui.QLineEdit(self.groupBoxFlotte)
        self.dBo.setGeometry(QtCore.QRect(60,224,60,18))
        self.dBo.setAlignment(QtCore.Qt.AlignRight)
        self.dBo.setObjectName("dBo")

        self.dSe = QtGui.QLineEdit(self.groupBoxFlotte)
        self.dSe.setGeometry(QtCore.QRect(60,204,60,18))
        self.dSe.setAlignment(QtCore.Qt.AlignRight)
        self.dSe.setObjectName("dSe")

        self.lTr = QtGui.QLabel(self.groupBoxFlotte)
        self.lTr.setGeometry(QtCore.QRect(4,304,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lTr.setFont(font)
        self.lTr.setWordWrap(False)
        self.lTr.setObjectName("lTr")

        self.lEm = QtGui.QLabel(self.groupBoxFlotte)
        self.lEm.setGeometry(QtCore.QRect(4,284,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lEm.setFont(font)
        self.lEm.setWordWrap(False)
        self.lEm.setObjectName("lEm")

        self.aEm = QtGui.QLineEdit(self.groupBoxFlotte)
        self.aEm.setGeometry(QtCore.QRect(196,284,60,18))
        self.aEm.setAlignment(QtCore.Qt.AlignRight)
        self.aEm.setObjectName("aEm")

        self.aDe = QtGui.QLineEdit(self.groupBoxFlotte)
        self.aDe.setGeometry(QtCore.QRect(196,264,60,18))
        self.aDe.setAlignment(QtCore.Qt.AlignRight)
        self.aDe.setObjectName("aDe")

        self.aTr = QtGui.QLineEdit(self.groupBoxFlotte)
        self.aTr.setGeometry(QtCore.QRect(196,304,60,18))
        self.aTr.setAlignment(QtCore.Qt.AlignRight)
        self.aTr.setObjectName("aTr")

        self.dTr = QtGui.QLineEdit(self.groupBoxFlotte)
        self.dTr.setGeometry(QtCore.QRect(60,304,60,18))
        self.dTr.setAlignment(QtCore.Qt.AlignRight)
        self.dTr.setObjectName("dTr")

        self.lPt = QtGui.QLabel(self.groupBoxFlotte)
        self.lPt.setGeometry(QtCore.QRect(4,44,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lPt.setFont(font)
        self.lPt.setWordWrap(False)
        self.lPt.setObjectName("lPt")

        self.swapFlottes = QtGui.QPushButton(self.groupBoxFlotte)
        self.swapFlottes.setGeometry(QtCore.QRect(144,24,26,18))
        self.swapFlottes.setFocusPolicy(QtCore.Qt.NoFocus)
        self.swapFlottes.setObjectName("swapFlottes")

        self.lDef = QtGui.QLabel(self.groupBoxFlotte)
        self.lDef.setGeometry(QtCore.QRect(28,24,59,16))
        self.lDef.setObjectName("lDef")

        self.lAtt = QtGui.QLabel(self.groupBoxFlotte)
        self.lAtt.setGeometry(QtCore.QRect(204,24,57,16))
        self.lAtt.setObjectName("lAtt")

        self.saveDef = QtGui.QPushButton(self.groupBoxFlotte)
        self.saveDef.setGeometry(QtCore.QRect(92,24,20,18))
        self.saveDef.setFocusPolicy(QtCore.Qt.NoFocus)
        self.saveDef.setObjectName("saveDef")

        self.nextWave = QtGui.QPushButton(self.groupBoxFlotte)
        self.nextWave.setGeometry(QtCore.QRect(308,24,20,18))
        self.nextWave.setFocusPolicy(QtCore.Qt.NoFocus)
        self.nextWave.setObjectName("nextWave")

        self.haveEngeener = QtGui.QCheckBox(self.groupBoxFlotte)
        self.haveEngeener.setGeometry(QtCore.QRect(288,20,14,21))
        self.haveEngeener.setFocusPolicy(QtCore.Qt.NoFocus)
        self.haveEngeener.setObjectName("haveEngeener")

        self.groupBoxDefense = QtGui.QGroupBox(simulatorWidget)
        self.groupBoxDefense.setGeometry(QtCore.QRect(4,336,197,209))
        self.groupBoxDefense.setObjectName("groupBoxDefense")

        self.dPb = QtGui.QLineEdit(self.groupBoxDefense)
        self.dPb.setGeometry(QtCore.QRect(60,144,60,18))
        self.dPb.setAlignment(QtCore.Qt.AlignRight)
        self.dPb.setObjectName("dPb")

        self.ldLo = QtGui.QLabel(self.groupBoxDefense)
        self.ldLo.setGeometry(QtCore.QRect(124,64,68,18))
        self.ldLo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldLo.setWordWrap(False)
        self.ldLo.setObjectName("ldLo")

        self.dGb = QtGui.QLineEdit(self.groupBoxDefense)
        self.dGb.setGeometry(QtCore.QRect(60,164,60,18))
        self.dGb.setAlignment(QtCore.Qt.AlignRight)
        self.dGb.setObjectName("dGb")

        self.lLe = QtGui.QLabel(self.groupBoxDefense)
        self.lLe.setGeometry(QtCore.QRect(4,44,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lLe.setFont(font)
        self.lLe.setWordWrap(False)
        self.lLe.setObjectName("lLe")

        self.dAi = QtGui.QLineEdit(self.groupBoxDefense)
        self.dAi.setGeometry(QtCore.QRect(60,104,60,18))
        self.dAi.setAlignment(QtCore.Qt.AlignRight)
        self.dAi.setObjectName("dAi")

        self.dLp = QtGui.QLineEdit(self.groupBoxDefense)
        self.dLp.setGeometry(QtCore.QRect(60,124,60,18))
        self.dLp.setAlignment(QtCore.Qt.AlignRight)
        self.dLp.setObjectName("dLp")

        self.ldCg = QtGui.QLabel(self.groupBoxDefense)
        self.ldCg.setGeometry(QtCore.QRect(124,84,68,18))
        self.ldCg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldCg.setWordWrap(False)
        self.ldCg.setObjectName("ldCg")

        self.lCg = QtGui.QLabel(self.groupBoxDefense)
        self.lCg.setGeometry(QtCore.QRect(4,84,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lCg.setFont(font)
        self.lCg.setWordWrap(False)
        self.lCg.setObjectName("lCg")

        self.lLp = QtGui.QLabel(self.groupBoxDefense)
        self.lLp.setGeometry(QtCore.QRect(4,124,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lLp.setFont(font)
        self.lLp.setWordWrap(False)
        self.lLp.setObjectName("lLp")

        self.ldAi = QtGui.QLabel(self.groupBoxDefense)
        self.ldAi.setGeometry(QtCore.QRect(124,104,68,18))
        self.ldAi.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldAi.setWordWrap(False)
        self.ldAi.setObjectName("ldAi")

        self.lLo = QtGui.QLabel(self.groupBoxDefense)
        self.lLo.setGeometry(QtCore.QRect(4,64,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lLo.setFont(font)
        self.lLo.setWordWrap(False)
        self.lLo.setObjectName("lLo")

        self.ldPb = QtGui.QLabel(self.groupBoxDefense)
        self.ldPb.setGeometry(QtCore.QRect(124,144,68,18))
        self.ldPb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldPb.setWordWrap(False)
        self.ldPb.setObjectName("ldPb")

        self.ldLp = QtGui.QLabel(self.groupBoxDefense)
        self.ldLp.setGeometry(QtCore.QRect(124,124,68,18))
        self.ldLp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldLp.setWordWrap(False)
        self.ldLp.setObjectName("ldLp")

        self.ldGb = QtGui.QLabel(self.groupBoxDefense)
        self.ldGb.setGeometry(QtCore.QRect(124,164,68,18))
        self.ldGb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldGb.setWordWrap(False)
        self.ldGb.setObjectName("ldGb")

        self.dCg = QtGui.QLineEdit(self.groupBoxDefense)
        self.dCg.setGeometry(QtCore.QRect(60,84,60,18))
        self.dCg.setAlignment(QtCore.Qt.AlignRight)
        self.dCg.setObjectName("dCg")

        self.lAi = QtGui.QLabel(self.groupBoxDefense)
        self.lAi.setGeometry(QtCore.QRect(4,104,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lAi.setFont(font)
        self.lAi.setWordWrap(False)
        self.lAi.setObjectName("lAi")

        self.lGb = QtGui.QLabel(self.groupBoxDefense)
        self.lGb.setGeometry(QtCore.QRect(4,164,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lGb.setFont(font)
        self.lGb.setWordWrap(False)
        self.lGb.setObjectName("lGb")

        self.lPb = QtGui.QLabel(self.groupBoxDefense)
        self.lPb.setGeometry(QtCore.QRect(4,144,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lPb.setFont(font)
        self.lPb.setWordWrap(False)
        self.lPb.setObjectName("lPb")

        self.dLm = QtGui.QLineEdit(self.groupBoxDefense)
        self.dLm.setGeometry(QtCore.QRect(60,24,60,18))
        self.dLm.setAlignment(QtCore.Qt.AlignRight)
        self.dLm.setObjectName("dLm")

        self.dLe = QtGui.QLineEdit(self.groupBoxDefense)
        self.dLe.setGeometry(QtCore.QRect(60,44,60,18))
        self.dLe.setAlignment(QtCore.Qt.AlignRight)
        self.dLe.setObjectName("dLe")

        self.dLo = QtGui.QLineEdit(self.groupBoxDefense)
        self.dLo.setGeometry(QtCore.QRect(60,64,60,18))
        self.dLo.setAlignment(QtCore.Qt.AlignRight)
        self.dLo.setObjectName("dLo")

        self.lLm = QtGui.QLabel(self.groupBoxDefense)
        self.lLm.setGeometry(QtCore.QRect(4,24,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lLm.setFont(font)
        self.lLm.setWordWrap(False)
        self.lLm.setObjectName("lLm")

        self.ldLm = QtGui.QLabel(self.groupBoxDefense)
        self.ldLm.setGeometry(QtCore.QRect(124,24,68,18))
        self.ldLm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldLm.setWordWrap(False)
        self.ldLm.setObjectName("ldLm")

        self.ldle = QtGui.QLabel(self.groupBoxDefense)
        self.ldle.setGeometry(QtCore.QRect(124,44,68,18))
        self.ldle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldle.setWordWrap(False)
        self.ldle.setObjectName("ldle")

        self.lMi = QtGui.QLabel(self.groupBoxDefense)
        self.lMi.setGeometry(QtCore.QRect(4,184,55,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lMi.setFont(font)
        self.lMi.setObjectName("lMi")

        self.ldMi = QtGui.QLabel(self.groupBoxDefense)
        self.ldMi.setGeometry(QtCore.QRect(124,184,68,16))
        self.ldMi.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ldMi.setObjectName("ldMi")

        self.dMi = QtGui.QLineEdit(self.groupBoxDefense)
        self.dMi.setGeometry(QtCore.QRect(60,184,60,18))
        self.dMi.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dMi.setObjectName("dMi")

        self.groupBoxTech = QtGui.QGroupBox(simulatorWidget)
        self.groupBoxTech.setGeometry(QtCore.QRect(204,336,133,101))
        self.groupBoxTech.setObjectName("groupBoxTech")

        self.lTar = QtGui.QLabel(self.groupBoxTech)
        self.lTar.setGeometry(QtCore.QRect(4,31,16,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lTar.setFont(font)
        self.lTar.setWordWrap(False)
        self.lTar.setObjectName("lTar")

        self.lTim = QtGui.QLabel(self.groupBoxTech)
        self.lTim.setGeometry(QtCore.QRect(80,56,16,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lTim.setFont(font)
        self.lTim.setWordWrap(False)
        self.lTim.setObjectName("lTim")

        self.lTbo = QtGui.QLabel(self.groupBoxTech)
        self.lTbo.setGeometry(QtCore.QRect(4,55,16,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lTbo.setFont(font)
        self.lTbo.setWordWrap(False)
        self.lTbo.setObjectName("lTbo")

        self.lThy = QtGui.QLabel(self.groupBoxTech)
        self.lThy.setGeometry(QtCore.QRect(80,80,16,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lThy.setFont(font)
        self.lThy.setWordWrap(False)
        self.lThy.setObjectName("lThy")

        self.tekDboucl = QtGui.QLineEdit(self.groupBoxTech)
        self.tekDboucl.setGeometry(QtCore.QRect(20,55,24,18))
        self.tekDboucl.setMaxLength(2)
        self.tekDboucl.setAlignment(QtCore.Qt.AlignRight)
        self.tekDboucl.setObjectName("tekDboucl")

        self.lTdef = QtGui.QLabel(self.groupBoxTech)
        self.lTdef.setGeometry(QtCore.QRect(20,18,24,18))

        font = QtGui.QFont()
        font.setPointSize(7)
        self.lTdef.setFont(font)
        self.lTdef.setWordWrap(False)
        self.lTdef.setObjectName("lTdef")

        self.lTpr = QtGui.QLabel(self.groupBoxTech)
        self.lTpr.setGeometry(QtCore.QRect(4,79,16,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lTpr.setFont(font)
        self.lTpr.setWordWrap(False)
        self.lTpr.setObjectName("lTpr")

        self.tekAboucl = QtGui.QLineEdit(self.groupBoxTech)
        self.tekAboucl.setGeometry(QtCore.QRect(52,55,24,18))
        self.tekAboucl.setMaxLength(2)
        self.tekAboucl.setAlignment(QtCore.Qt.AlignRight)
        self.tekAboucl.setObjectName("tekAboucl")

        self.tekAprotec = QtGui.QLineEdit(self.groupBoxTech)
        self.tekAprotec.setGeometry(QtCore.QRect(52,79,24,18))
        self.tekAprotec.setMaxLength(2)
        self.tekAprotec.setAlignment(QtCore.Qt.AlignRight)
        self.tekAprotec.setObjectName("tekAprotec")

        self.lTco = QtGui.QLabel(self.groupBoxTech)
        self.lTco.setGeometry(QtCore.QRect(80,32,16,18))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lTco.setFont(font)
        self.lTco.setWordWrap(False)
        self.lTco.setObjectName("lTco")

        self.tekHyp = QtGui.QLineEdit(self.groupBoxTech)
        self.tekHyp.setGeometry(QtCore.QRect(96,79,24,18))
        self.tekHyp.setMaxLength(2)
        self.tekHyp.setAlignment(QtCore.Qt.AlignRight)
        self.tekHyp.setObjectName("tekHyp")

        self.lTprop = QtGui.QLabel(self.groupBoxTech)
        self.lTprop.setGeometry(QtCore.QRect(96,18,26,18))

        font = QtGui.QFont()
        font.setPointSize(7)
        self.lTprop.setFont(font)
        self.lTprop.setWordWrap(False)
        self.lTprop.setObjectName("lTprop")

        self.tekComb = QtGui.QLineEdit(self.groupBoxTech)
        self.tekComb.setGeometry(QtCore.QRect(96,31,24,18))
        self.tekComb.setMaxLength(2)
        self.tekComb.setAlignment(QtCore.Qt.AlignRight)
        self.tekComb.setObjectName("tekComb")

        self.tekImp = QtGui.QLineEdit(self.groupBoxTech)
        self.tekImp.setGeometry(QtCore.QRect(96,55,24,18))
        self.tekImp.setMaxLength(2)
        self.tekImp.setAlignment(QtCore.Qt.AlignRight)
        self.tekImp.setObjectName("tekImp")

        self.lTatt = QtGui.QLabel(self.groupBoxTech)
        self.lTatt.setGeometry(QtCore.QRect(60,18,24,18))

        font = QtGui.QFont()
        font.setPointSize(7)
        self.lTatt.setFont(font)
        self.lTatt.setWordWrap(False)
        self.lTatt.setObjectName("lTatt")

        self.tekDarmes = QtGui.QLineEdit(self.groupBoxTech)
        self.tekDarmes.setGeometry(QtCore.QRect(20,31,24,18))
        self.tekDarmes.setMaxLength(2)
        self.tekDarmes.setAlignment(QtCore.Qt.AlignRight)
        self.tekDarmes.setObjectName("tekDarmes")

        self.tekAarmes = QtGui.QLineEdit(self.groupBoxTech)
        self.tekAarmes.setGeometry(QtCore.QRect(52,31,24,18))
        self.tekAarmes.setMaxLength(2)
        self.tekAarmes.setAlignment(QtCore.Qt.AlignRight)
        self.tekAarmes.setObjectName("tekAarmes")

        self.tekDprotec = QtGui.QLineEdit(self.groupBoxTech)
        self.tekDprotec.setGeometry(QtCore.QRect(20,79,24,18))
        self.tekDprotec.setMaxLength(2)
        self.tekDprotec.setAlignment(QtCore.Qt.AlignRight)
        self.tekDprotec.setObjectName("tekDprotec")

        self.groupBoxRess = QtGui.QGroupBox(simulatorWidget)
        self.groupBoxRess.setGeometry(QtCore.QRect(212,440,117,105))
        self.groupBoxRess.setObjectName("groupBoxRess")

        self.ressD = QtGui.QLineEdit(self.groupBoxRess)
        self.ressD.setGeometry(QtCore.QRect(16,60,89,18))
        self.ressD.setAlignment(QtCore.Qt.AlignRight)
        self.ressD.setObjectName("ressD")

        self.ressC = QtGui.QLineEdit(self.groupBoxRess)
        self.ressC.setGeometry(QtCore.QRect(16,40,89,18))
        self.ressC.setAlignment(QtCore.Qt.AlignRight)
        self.ressC.setObjectName("ressC")

        self.ressM = QtGui.QLineEdit(self.groupBoxRess)
        self.ressM.setGeometry(QtCore.QRect(16,20,89,18))
        self.ressM.setAlignment(QtCore.Qt.AlignRight)
        self.ressM.setObjectName("ressM")

        self.labelFret = QtGui.QLabel(self.groupBoxRess)
        self.labelFret.setGeometry(QtCore.QRect(4,84,53,16))
        self.labelFret.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFret.setObjectName("labelFret")

        self.comboBoxFret = QtGui.QComboBox(self.groupBoxRess)
        self.comboBoxFret.setGeometry(QtCore.QRect(60,80,54,22))
        self.comboBoxFret.setObjectName("comboBoxFret")

        self.results = QtGui.QTabWidget(simulatorWidget)
        self.results.setGeometry(QtCore.QRect(340,136,460,409))
        self.results.setFocusPolicy(QtCore.Qt.NoFocus)
        self.results.setTabShape(QtGui.QTabWidget.Rounded)
        self.results.setObjectName("results")

        self.tabResult = QtGui.QWidget()
        self.tabResult.setObjectName("tabResult")

        self.lReSim = QtGui.QLabel(self.tabResult)
        self.lReSim.setGeometry(QtCore.QRect(16,12,80,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lReSim.setFont(font)
        self.lReSim.setWordWrap(False)
        self.lReSim.setObjectName("lReSim")

        self.rnbRounds = QtGui.QLabel(self.tabResult)
        self.rnbRounds.setGeometry(QtCore.QRect(196,12,101,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.rnbRounds.setFont(font)
        self.rnbRounds.setWordWrap(False)
        self.rnbRounds.setObjectName("rnbRounds")

        self.lReRes = QtGui.QLabel(self.tabResult)
        self.lReRes.setGeometry(QtCore.QRect(16,32,62,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lReRes.setFont(font)
        self.lReRes.setWordWrap(False)
        self.lReRes.setObjectName("lReRes")

        self.lReTou = QtGui.QLabel(self.tabResult)
        self.lReTou.setGeometry(QtCore.QRect(156,12,40,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lReTou.setFont(font)
        self.lReTou.setWordWrap(False)
        self.lReTou.setObjectName("lReTou")

        self.labelResult = QtGui.QLabel(self.tabResult)
        self.labelResult.setGeometry(QtCore.QRect(86,32,351,21))
        self.labelResult.setWordWrap(False)
        self.labelResult.setObjectName("labelResult")

        self.rnbSims = QtGui.QLabel(self.tabResult)
        self.rnbSims.setGeometry(QtCore.QRect(96,12,50,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.rnbSims.setFont(font)
        self.rnbSims.setWordWrap(False)
        self.rnbSims.setObjectName("rnbSims")

        self.line = QtGui.QFrame(self.tabResult)
        self.line.setGeometry(QtCore.QRect(8,52,441,16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")

        self.lRePer = QtGui.QLabel(self.tabResult)
        self.lRePer.setGeometry(QtCore.QRect(16,72,51,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lRePer.setFont(font)
        self.lRePer.setWordWrap(False)
        self.lRePer.setObjectName("lRePer")

        self.labelPertes = QtGui.QLabel(self.tabResult)
        self.labelPertes.setGeometry(QtCore.QRect(66,72,370,20))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelPertes.setFont(font)
        self.labelPertes.setWordWrap(False)
        self.labelPertes.setObjectName("labelPertes")

        self.lReCdrd = QtGui.QLabel(self.tabResult)
        self.lReCdrd.setGeometry(QtCore.QRect(16,92,50,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lReCdrd.setFont(font)
        self.lReCdrd.setWordWrap(False)
        self.lReCdrd.setObjectName("lReCdrd")

        self.labelCdr = QtGui.QLabel(self.tabResult)
        self.labelCdr.setGeometry(QtCore.QRect(66,92,370,20))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelCdr.setFont(font)
        self.labelCdr.setWordWrap(False)
        self.labelCdr.setObjectName("labelCdr")

        self.lReGaid = QtGui.QLabel(self.tabResult)
        self.lReGaid.setGeometry(QtCore.QRect(16,112,50,20))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lReGaid.setFont(font)
        self.lReGaid.setWordWrap(False)
        self.lReGaid.setObjectName("lReGaid")

        self.labelGains = QtGui.QLabel(self.tabResult)
        self.labelGains.setGeometry(QtCore.QRect(66,112,370,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelGains.setFont(font)
        self.labelGains.setWordWrap(False)
        self.labelGains.setObjectName("labelGains")

        self.line_2 = QtGui.QFrame(self.tabResult)
        self.line_2.setGeometry(QtCore.QRect(8,136,441,16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.lReButT = QtGui.QLabel(self.tabResult)
        self.lReButT.setGeometry(QtCore.QRect(16,152,54,20))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lReButT.setFont(font)
        self.lReButT.setWordWrap(False)
        self.lReButT.setObjectName("lReButT")

        self.lReButR = QtGui.QLabel(self.tabResult)
        self.lReButR.setGeometry(QtCore.QRect(16,172,54,20))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lReButR.setFont(font)
        self.lReButR.setWordWrap(False)
        self.lReButR.setObjectName("lReButR")

        self.buttinR = QtGui.QLabel(self.tabResult)
        self.buttinR.setGeometry(QtCore.QRect(66,172,370,20))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttinR.setFont(font)
        self.buttinR.setWordWrap(False)
        self.buttinR.setObjectName("buttinR")

        self.buttinT = QtGui.QLabel(self.tabResult)
        self.buttinT.setGeometry(QtCore.QRect(66,152,370,20))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttinT.setFont(font)
        self.buttinT.setWordWrap(False)
        self.buttinT.setObjectName("buttinT")

        self.line_3 = QtGui.QFrame(self.tabResult)
        self.line_3.setGeometry(QtCore.QRect(8,192,441,16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.lReTot = QtGui.QLabel(self.tabResult)
        self.lReTot.setGeometry(QtCore.QRect(16,212,40,20))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lReTot.setFont(font)
        self.lReTot.setWordWrap(False)
        self.lReTot.setObjectName("lReTot")

        self.labelTotal = QtGui.QLabel(self.tabResult)
        self.labelTotal.setGeometry(QtCore.QRect(56,212,380,20))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelTotal.setFont(font)
        self.labelTotal.setWordWrap(False)
        self.labelTotal.setObjectName("labelTotal")

        self.line_4 = QtGui.QFrame(self.tabResult)
        self.line_4.setGeometry(QtCore.QRect(8,236,441,17))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")

        self.lRePeD = QtGui.QLabel(self.tabResult)
        self.lRePeD.setGeometry(QtCore.QRect(16,292,63,20))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lRePeD.setFont(font)
        self.lRePeD.setWordWrap(False)
        self.lRePeD.setObjectName("lRePeD")

        self.labelPertesDmin = QtGui.QLabel(self.tabResult)
        self.labelPertesDmin.setGeometry(QtCore.QRect(86,292,100,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelPertesDmin.setFont(font)
        self.labelPertesDmin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPertesDmin.setWordWrap(False)
        self.labelPertesDmin.setObjectName("labelPertesDmin")

        self.labelCdrMoy = QtGui.QLabel(self.tabResult)
        self.labelCdrMoy.setGeometry(QtCore.QRect(212,312,100,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelCdrMoy.setFont(font)
        self.labelCdrMoy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCdrMoy.setWordWrap(False)
        self.labelCdrMoy.setObjectName("labelCdrMoy")

        self.labelPertesAmoy = QtGui.QLabel(self.tabResult)
        self.labelPertesAmoy.setGeometry(QtCore.QRect(212,272,100,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelPertesAmoy.setFont(font)
        self.labelPertesAmoy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPertesAmoy.setWordWrap(False)
        self.labelPertesAmoy.setObjectName("labelPertesAmoy")

        self.labelRecyMoy = QtGui.QLabel(self.tabResult)
        self.labelRecyMoy.setGeometry(QtCore.QRect(212,352,100,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelRecyMoy.setFont(font)
        self.labelRecyMoy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRecyMoy.setWordWrap(False)
        self.labelRecyMoy.setObjectName("labelRecyMoy")

        self.labelCdrMin = QtGui.QLabel(self.tabResult)
        self.labelCdrMin.setGeometry(QtCore.QRect(86,312,100,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelCdrMin.setFont(font)
        self.labelCdrMin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCdrMin.setWordWrap(False)
        self.labelCdrMin.setObjectName("labelCdrMin")

        self.lReMin = QtGui.QLabel(self.tabResult)
        self.lReMin.setGeometry(QtCore.QRect(105,252,61,20))

        font = QtGui.QFont()
        font.setPointSize(7)
        self.lReMin.setFont(font)
        self.lReMin.setAlignment(QtCore.Qt.AlignCenter)
        self.lReMin.setWordWrap(False)
        self.lReMin.setObjectName("lReMin")

        self.lReGai = QtGui.QLabel(self.tabResult)
        self.lReGai.setGeometry(QtCore.QRect(16,332,60,20))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lReGai.setFont(font)
        self.lReGai.setWordWrap(False)
        self.lReGai.setObjectName("lReGai")

        self.lReMoy = QtGui.QLabel(self.tabResult)
        self.lReMoy.setGeometry(QtCore.QRect(232,252,61,20))

        font = QtGui.QFont()
        font.setPointSize(7)
        self.lReMoy.setFont(font)
        self.lReMoy.setAlignment(QtCore.Qt.AlignCenter)
        self.lReMoy.setWordWrap(False)
        self.lReMoy.setObjectName("lReMoy")

        self.labelPertesAmax = QtGui.QLabel(self.tabResult)
        self.labelPertesAmax.setGeometry(QtCore.QRect(336,272,100,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelPertesAmax.setFont(font)
        self.labelPertesAmax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPertesAmax.setWordWrap(False)
        self.labelPertesAmax.setObjectName("labelPertesAmax")

        self.labelRecyMin = QtGui.QLabel(self.tabResult)
        self.labelRecyMin.setGeometry(QtCore.QRect(86,352,100,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelRecyMin.setFont(font)
        self.labelRecyMin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRecyMin.setWordWrap(False)
        self.labelRecyMin.setObjectName("labelRecyMin")

        self.lRePeA = QtGui.QLabel(self.tabResult)
        self.lRePeA.setGeometry(QtCore.QRect(16,272,62,20))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lRePeA.setFont(font)
        self.lRePeA.setWordWrap(False)
        self.lRePeA.setObjectName("lRePeA")

        self.labelPertesAmin = QtGui.QLabel(self.tabResult)
        self.labelPertesAmin.setGeometry(QtCore.QRect(86,272,100,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelPertesAmin.setFont(font)
        self.labelPertesAmin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPertesAmin.setWordWrap(False)
        self.labelPertesAmin.setObjectName("labelPertesAmin")

        self.line1 = QtGui.QFrame(self.tabResult)
        self.line1.setGeometry(QtCore.QRect(186,253,20,120))
        self.line1.setFrameShape(QtGui.QFrame.VLine)
        self.line1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line1.setFrameShape(QtGui.QFrame.VLine)
        self.line1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line1.setObjectName("line1")

        self.labelPertesDmoy = QtGui.QLabel(self.tabResult)
        self.labelPertesDmoy.setGeometry(QtCore.QRect(212,292,100,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelPertesDmoy.setFont(font)
        self.labelPertesDmoy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPertesDmoy.setWordWrap(False)
        self.labelPertesDmoy.setObjectName("labelPertesDmoy")

        self.labelPertesDmax = QtGui.QLabel(self.tabResult)
        self.labelPertesDmax.setGeometry(QtCore.QRect(336,292,100,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelPertesDmax.setFont(font)
        self.labelPertesDmax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPertesDmax.setWordWrap(False)
        self.labelPertesDmax.setObjectName("labelPertesDmax")

        self.labelGainsMoy = QtGui.QLabel(self.tabResult)
        self.labelGainsMoy.setGeometry(QtCore.QRect(212,332,100,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelGainsMoy.setFont(font)
        self.labelGainsMoy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelGainsMoy.setWordWrap(False)
        self.labelGainsMoy.setObjectName("labelGainsMoy")

        self.lReMax = QtGui.QLabel(self.tabResult)
        self.lReMax.setGeometry(QtCore.QRect(356,252,69,20))

        font = QtGui.QFont()
        font.setPointSize(7)
        self.lReMax.setFont(font)
        self.lReMax.setAlignment(QtCore.Qt.AlignCenter)
        self.lReMax.setWordWrap(False)
        self.lReMax.setObjectName("lReMax")

        self.lReCdr = QtGui.QLabel(self.tabResult)
        self.lReCdr.setGeometry(QtCore.QRect(16,312,60,20))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lReCdr.setFont(font)
        self.lReCdr.setWordWrap(False)
        self.lReCdr.setObjectName("lReCdr")

        self.lReRec = QtGui.QLabel(self.tabResult)
        self.lReRec.setGeometry(QtCore.QRect(16,352,60,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.lReRec.setFont(font)
        self.lReRec.setWordWrap(False)
        self.lReRec.setObjectName("lReRec")

        self.labelGainsMax = QtGui.QLabel(self.tabResult)
        self.labelGainsMax.setGeometry(QtCore.QRect(336,332,100,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelGainsMax.setFont(font)
        self.labelGainsMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelGainsMax.setWordWrap(False)
        self.labelGainsMax.setObjectName("labelGainsMax")

        self.labelGainsMin = QtGui.QLabel(self.tabResult)
        self.labelGainsMin.setGeometry(QtCore.QRect(86,332,100,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelGainsMin.setFont(font)
        self.labelGainsMin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelGainsMin.setWordWrap(False)
        self.labelGainsMin.setObjectName("labelGainsMin")

        self.labelRecyMax = QtGui.QLabel(self.tabResult)
        self.labelRecyMax.setGeometry(QtCore.QRect(336,352,100,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelRecyMax.setFont(font)
        self.labelRecyMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelRecyMax.setWordWrap(False)
        self.labelRecyMax.setObjectName("labelRecyMax")

        self.line1_2 = QtGui.QFrame(self.tabResult)
        self.line1_2.setGeometry(QtCore.QRect(316,252,20,120))
        self.line1_2.setFrameShape(QtGui.QFrame.VLine)
        self.line1_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line1_2.setFrameShape(QtGui.QFrame.VLine)
        self.line1_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line1_2.setObjectName("line1_2")

        self.labelCdrMax = QtGui.QLabel(self.tabResult)
        self.labelCdrMax.setGeometry(QtCore.QRect(336,312,100,21))

        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelCdrMax.setFont(font)
        self.labelCdrMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCdrMax.setWordWrap(False)
        self.labelCdrMax.setObjectName("labelCdrMax")
        self.results.addTab(self.tabResult,"")

        self.tabGraph = QtGui.QWidget()
        self.tabGraph.setObjectName("tabGraph")

        self.histoBarSlider = QtGui.QSlider(self.tabGraph)
        self.histoBarSlider.setGeometry(QtCore.QRect(8,92,160,16))
        self.histoBarSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.histoBarSlider.setMinimum(2)
        self.histoBarSlider.setMaximum(50)
        self.histoBarSlider.setProperty("value",QtCore.QVariant(15))
        self.histoBarSlider.setOrientation(QtCore.Qt.Horizontal)
        self.histoBarSlider.setObjectName("histoBarSlider")

        self.comboBoxChooseHisto = QtGui.QComboBox(self.tabGraph)
        self.comboBoxChooseHisto.setGeometry(QtCore.QRect(8,36,149,22))
        self.comboBoxChooseHisto.setObjectName("comboBoxChooseHisto")
        self.results.addTab(self.tabGraph,"")

        self.tabAtt = QtGui.QWidget()
        self.tabAtt.setObjectName("tabAtt")

        self.aDetails = QtGui.QTextBrowser(self.tabAtt)
        self.aDetails.setGeometry(QtCore.QRect(-3,0,461,385))
        self.aDetails.setObjectName("aDetails")
        self.results.addTab(self.tabAtt,"")

        self.tabDef = QtGui.QWidget()
        self.tabDef.setObjectName("tabDef")

        self.dDetails = QtGui.QTextBrowser(self.tabDef)
        self.dDetails.setGeometry(QtCore.QRect(-3,0,461,385))
        self.dDetails.setObjectName("dDetails")
        self.results.addTab(self.tabDef,"")

        self.groupBoxTrajet = QtGui.QGroupBox(simulatorWidget)
        self.groupBoxTrajet.setGeometry(QtCore.QRect(484,4,313,117))
        self.groupBoxTrajet.setObjectName("groupBoxTrajet")

        self.lTrPo = QtGui.QLabel(self.groupBoxTrajet)
        self.lTrPo.setGeometry(QtCore.QRect(184,60,16,18))
        self.lTrPo.setWordWrap(False)
        self.lTrPo.setObjectName("lTrPo")

        self.lTrvit = QtGui.QLabel(self.groupBoxTrajet)
        self.lTrvit.setGeometry(QtCore.QRect(207,20,53,16))

        font = QtGui.QFont()
        font.setPointSize(7)
        self.lTrvit.setFont(font)
        self.lTrvit.setWordWrap(False)
        self.lTrvit.setObjectName("lTrvit")

        self.lTrCib = QtGui.QLabel(self.groupBoxTrajet)
        self.lTrCib.setGeometry(QtCore.QRect(104,20,32,16))

        font = QtGui.QFont()
        font.setPointSize(7)
        self.lTrCib.setFont(font)
        self.lTrCib.setWordWrap(False)
        self.lTrCib.setObjectName("lTrCib")

        self.phalLCD = QtGui.QLCDNumber(self.groupBoxTrajet)
        self.phalLCD.setGeometry(QtCore.QRect(8,88,165,18))
        self.phalLCD.setFrameShape(QtGui.QFrame.Panel)
        self.phalLCD.setFrameShadow(QtGui.QFrame.Sunken)
        self.phalLCD.setNumDigits(19)
        self.phalLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.phalLCD.setProperty("value",QtCore.QVariant(0.0))
        self.phalLCD.setObjectName("phalLCD")

        self.timeLcd = QtGui.QLCDNumber(self.groupBoxTrajet)
        self.timeLcd.setGeometry(QtCore.QRect(183,88,120,18))
        self.timeLcd.setFrameShape(QtGui.QFrame.Panel)
        self.timeLcd.setFrameShadow(QtGui.QFrame.Sunken)
        self.timeLcd.setNumDigits(12)
        self.timeLcd.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.timeLcd.setProperty("value",QtCore.QVariant(0.0))
        self.timeLcd.setObjectName("timeLcd")

        self.lTrDep = QtGui.QLabel(self.groupBoxTrajet)
        self.lTrDep.setGeometry(QtCore.QRect(24,20,40,16))

        font = QtGui.QFont()
        font.setPointSize(7)
        self.lTrDep.setFont(font)
        self.lTrDep.setWordWrap(False)
        self.lTrDep.setObjectName("lTrDep")

        self.vitesse = QtGui.QSlider(self.groupBoxTrajet)
        self.vitesse.setGeometry(QtCore.QRect(156,38,149,18))
        self.vitesse.setFocusPolicy(QtCore.Qt.NoFocus)
        self.vitesse.setMinimum(10)
        self.vitesse.setMaximum(100)
        self.vitesse.setProperty("value",QtCore.QVariant(100))
        self.vitesse.setOrientation(QtCore.Qt.Horizontal)
        self.vitesse.setObjectName("vitesse")

        self.cible = QtGui.QLineEdit(self.groupBoxTrajet)
        self.cible.setGeometry(QtCore.QRect(88,36,60,18))
        self.cible.setObjectName("cible")

        self.vitesseLcd = QtGui.QLCDNumber(self.groupBoxTrajet)
        self.vitesseLcd.setGeometry(QtCore.QRect(151,62,30,18))
        self.vitesseLcd.setFrameShape(QtGui.QFrame.Panel)
        self.vitesseLcd.setFrameShadow(QtGui.QFrame.Sunken)
        self.vitesseLcd.setNumDigits(3)
        self.vitesseLcd.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.vitesseLcd.setProperty("value",QtCore.QVariant(100.0))
        self.vitesseLcd.setObjectName("vitesseLcd")

        self.deutLcd = QtGui.QLCDNumber(self.groupBoxTrajet)
        self.deutLcd.setGeometry(QtCore.QRect(202,62,101,18))
        self.deutLcd.setFrameShape(QtGui.QFrame.Panel)
        self.deutLcd.setFrameShadow(QtGui.QFrame.Sunken)
        self.deutLcd.setNumDigits(10)
        self.deutLcd.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.deutLcd.setObjectName("deutLcd")

        self.phallange = QtGui.QDateTimeEdit(self.groupBoxTrajet)
        self.phallange.setGeometry(QtCore.QRect(6,60,141,22))
        self.phallange.setFocusPolicy(QtCore.Qt.NoFocus)
        self.phallange.setObjectName("phallange")

        self.depart = QtGui.QComboBox(self.groupBoxTrajet)
        self.depart.setGeometry(QtCore.QRect(8,36,77,18))
        self.depart.setEditable(True)
        self.depart.setObjectName("depart")

        self.copyPaste = QtGui.QLineEdit(simulatorWidget)
        self.copyPaste.setGeometry(QtCore.QRect(374,72,81,24))
        self.copyPaste.setFocusPolicy(QtCore.Qt.NoFocus)
        self.copyPaste.setObjectName("copyPaste")

        self.simuler = QtGui.QPushButton(simulatorWidget)
        self.simuler.setGeometry(QtCore.QRect(360,12,105,45))

        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.simuler.setFont(font)
        self.simuler.setCursor(QtCore.Qt.ArrowCursor)
        self.simuler.setFocusPolicy(QtCore.Qt.NoFocus)
        self.simuler.setObjectName("simuler")

        self.retranslateUi(simulatorWidget)
        self.results.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(simulatorWidget)
        simulatorWidget.setTabOrder(self.dPt,self.dGt)
        simulatorWidget.setTabOrder(self.dGt,self.dCle)
        simulatorWidget.setTabOrder(self.dCle,self.dClo)
        simulatorWidget.setTabOrder(self.dClo,self.dCro)
        simulatorWidget.setTabOrder(self.dCro,self.dVb)
        simulatorWidget.setTabOrder(self.dVb,self.dVc)
        simulatorWidget.setTabOrder(self.dVc,self.dRe)
        simulatorWidget.setTabOrder(self.dRe,self.dSe)
        simulatorWidget.setTabOrder(self.dSe,self.dBo)
        simulatorWidget.setTabOrder(self.dBo,self.dSs)
        simulatorWidget.setTabOrder(self.dSs,self.dDe)
        simulatorWidget.setTabOrder(self.dDe,self.dEm)
        simulatorWidget.setTabOrder(self.dEm,self.dTr)
        simulatorWidget.setTabOrder(self.dTr,self.dLm)
        simulatorWidget.setTabOrder(self.dLm,self.dLe)
        simulatorWidget.setTabOrder(self.dLe,self.dLo)
        simulatorWidget.setTabOrder(self.dLo,self.dCg)
        simulatorWidget.setTabOrder(self.dCg,self.dAi)
        simulatorWidget.setTabOrder(self.dAi,self.dLp)
        simulatorWidget.setTabOrder(self.dLp,self.dPb)
        simulatorWidget.setTabOrder(self.dPb,self.dGb)
        simulatorWidget.setTabOrder(self.dGb,self.dMi)
        simulatorWidget.setTabOrder(self.dMi,self.aPt)
        simulatorWidget.setTabOrder(self.aPt,self.aGt)
        simulatorWidget.setTabOrder(self.aGt,self.aCle)
        simulatorWidget.setTabOrder(self.aCle,self.aClo)
        simulatorWidget.setTabOrder(self.aClo,self.aCro)
        simulatorWidget.setTabOrder(self.aCro,self.aVb)
        simulatorWidget.setTabOrder(self.aVb,self.aVc)
        simulatorWidget.setTabOrder(self.aVc,self.aRe)
        simulatorWidget.setTabOrder(self.aRe,self.aSe)
        simulatorWidget.setTabOrder(self.aSe,self.aBo)
        simulatorWidget.setTabOrder(self.aBo,self.aDe)
        simulatorWidget.setTabOrder(self.aDe,self.aEm)
        simulatorWidget.setTabOrder(self.aEm,self.aTr)
        simulatorWidget.setTabOrder(self.aTr,self.tekDarmes)
        simulatorWidget.setTabOrder(self.tekDarmes,self.tekDboucl)
        simulatorWidget.setTabOrder(self.tekDboucl,self.tekDprotec)
        simulatorWidget.setTabOrder(self.tekDprotec,self.tekAarmes)
        simulatorWidget.setTabOrder(self.tekAarmes,self.tekAboucl)
        simulatorWidget.setTabOrder(self.tekAboucl,self.tekAprotec)
        simulatorWidget.setTabOrder(self.tekAprotec,self.tekComb)
        simulatorWidget.setTabOrder(self.tekComb,self.tekImp)
        simulatorWidget.setTabOrder(self.tekImp,self.tekHyp)
        simulatorWidget.setTabOrder(self.tekHyp,self.ressM)
        simulatorWidget.setTabOrder(self.ressM,self.ressC)
        simulatorWidget.setTabOrder(self.ressC,self.ressD)
        simulatorWidget.setTabOrder(self.ressD,self.cible)
        simulatorWidget.setTabOrder(self.cible,self.comboBoxFret)
        simulatorWidget.setTabOrder(self.comboBoxFret,self.aDetails)
        simulatorWidget.setTabOrder(self.aDetails,self.dDetails)

    def retranslateUi(self, simulatorWidget):
        simulatorWidget.setWindowTitle(QtGui.QApplication.translate("simulatorWidget", "simulatorWidget", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxFlotte.setTitle(QtGui.QApplication.translate("simulatorWidget", "Flotte", None, QtGui.QApplication.UnicodeUTF8))
        self.lRe.setText(QtGui.QApplication.translate("simulatorWidget", "Recycleur", None, QtGui.QApplication.UnicodeUTF8))
        self.lDe.setText(QtGui.QApplication.translate("simulatorWidget", "Destr.", None, QtGui.QApplication.UnicodeUTF8))
        self.lSs.setText(QtGui.QApplication.translate("simulatorWidget", "S. solaire", None, QtGui.QApplication.UnicodeUTF8))
        self.resetDef.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Cliquez pour effacer", None, QtGui.QApplication.UnicodeUTF8))
        self.resetDef.setText(QtGui.QApplication.translate("simulatorWidget", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.lClo.setText(QtGui.QApplication.translate("simulatorWidget", "Ch. lourd", None, QtGui.QApplication.UnicodeUTF8))
        self.lCr.setText(QtGui.QApplication.translate("simulatorWidget", "Croiseur", None, QtGui.QApplication.UnicodeUTF8))
        self.lBo.setText(QtGui.QApplication.translate("simulatorWidget", "Bomb.", None, QtGui.QApplication.UnicodeUTF8))
        self.lSe.setText(QtGui.QApplication.translate("simulatorWidget", "S. espio.", None, QtGui.QApplication.UnicodeUTF8))
        self.lVb.setText(QtGui.QApplication.translate("simulatorWidget", "V. bataille", None, QtGui.QApplication.UnicodeUTF8))
        self.lVc.setText(QtGui.QApplication.translate("simulatorWidget", "V. de colo", None, QtGui.QApplication.UnicodeUTF8))
        self.lCle.setText(QtGui.QApplication.translate("simulatorWidget", "Ch. léger", None, QtGui.QApplication.UnicodeUTF8))
        self.lGt.setText(QtGui.QApplication.translate("simulatorWidget", "G. transpo.", None, QtGui.QApplication.UnicodeUTF8))
        self.resetAtt.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Cliquez pour effacer", None, QtGui.QApplication.UnicodeUTF8))
        self.resetAtt.setText(QtGui.QApplication.translate("simulatorWidget", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.lTr.setText(QtGui.QApplication.translate("simulatorWidget", "Traqueur", None, QtGui.QApplication.UnicodeUTF8))
        self.lEm.setText(QtGui.QApplication.translate("simulatorWidget", "EDLM", None, QtGui.QApplication.UnicodeUTF8))
        self.lPt.setText(QtGui.QApplication.translate("simulatorWidget", "P. transpo.", None, QtGui.QApplication.UnicodeUTF8))
        self.swapFlottes.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Echanger les flottes", None, QtGui.QApplication.UnicodeUTF8))
        self.swapFlottes.setText(QtGui.QApplication.translate("simulatorWidget", "<->", None, QtGui.QApplication.UnicodeUTF8))
        self.lDef.setText(QtGui.QApplication.translate("simulatorWidget", "Défenseur", None, QtGui.QApplication.UnicodeUTF8))
        self.lAtt.setText(QtGui.QApplication.translate("simulatorWidget", "Attaquant", None, QtGui.QApplication.UnicodeUTF8))
        self.saveDef.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Sauvegarder la flotte", None, QtGui.QApplication.UnicodeUTF8))
        self.saveDef.setText(QtGui.QApplication.translate("simulatorWidget", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.nextWave.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Vague suivante", None, QtGui.QApplication.UnicodeUTF8))
        self.nextWave.setText(QtGui.QApplication.translate("simulatorWidget", "->", None, QtGui.QApplication.UnicodeUTF8))
        self.haveEngeener.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Le défenseur possède l\'officier ingénieur", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxDefense.setTitle(QtGui.QApplication.translate("simulatorWidget", "Défense", None, QtGui.QApplication.UnicodeUTF8))
        self.lLe.setText(QtGui.QApplication.translate("simulatorWidget", "L. léger", None, QtGui.QApplication.UnicodeUTF8))
        self.lCg.setText(QtGui.QApplication.translate("simulatorWidget", "C. gauss", None, QtGui.QApplication.UnicodeUTF8))
        self.lLp.setText(QtGui.QApplication.translate("simulatorWidget", "L. plasma", None, QtGui.QApplication.UnicodeUTF8))
        self.lLo.setText(QtGui.QApplication.translate("simulatorWidget", "L.lourd", None, QtGui.QApplication.UnicodeUTF8))
        self.lAi.setText(QtGui.QApplication.translate("simulatorWidget", "A. ions", None, QtGui.QApplication.UnicodeUTF8))
        self.lGb.setText(QtGui.QApplication.translate("simulatorWidget", "G. bouclier", None, QtGui.QApplication.UnicodeUTF8))
        self.lPb.setText(QtGui.QApplication.translate("simulatorWidget", "P. bouclier", None, QtGui.QApplication.UnicodeUTF8))
        self.lLm.setText(QtGui.QApplication.translate("simulatorWidget", "L. missile", None, QtGui.QApplication.UnicodeUTF8))
        self.lMi.setText(QtGui.QApplication.translate("simulatorWidget", "M. inter.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxTech.setTitle(QtGui.QApplication.translate("simulatorWidget", "Technologies", None, QtGui.QApplication.UnicodeUTF8))
        self.lTar.setText(QtGui.QApplication.translate("simulatorWidget", "Ar.", None, QtGui.QApplication.UnicodeUTF8))
        self.lTim.setText(QtGui.QApplication.translate("simulatorWidget", "im.", None, QtGui.QApplication.UnicodeUTF8))
        self.lTbo.setText(QtGui.QApplication.translate("simulatorWidget", "Bo.", None, QtGui.QApplication.UnicodeUTF8))
        self.lThy.setText(QtGui.QApplication.translate("simulatorWidget", "hy.", None, QtGui.QApplication.UnicodeUTF8))
        self.tekDboucl.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Technologie bouclier défenseur", None, QtGui.QApplication.UnicodeUTF8))
        self.lTdef.setText(QtGui.QApplication.translate("simulatorWidget", "Déf.", None, QtGui.QApplication.UnicodeUTF8))
        self.lTpr.setText(QtGui.QApplication.translate("simulatorWidget", "Pr.", None, QtGui.QApplication.UnicodeUTF8))
        self.tekAboucl.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Technologie bouclier attaquant", None, QtGui.QApplication.UnicodeUTF8))
        self.tekAprotec.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Technologie protection attaquant", None, QtGui.QApplication.UnicodeUTF8))
        self.lTco.setText(QtGui.QApplication.translate("simulatorWidget", "co.", None, QtGui.QApplication.UnicodeUTF8))
        self.tekHyp.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Technologie hyperespace", None, QtGui.QApplication.UnicodeUTF8))
        self.lTprop.setText(QtGui.QApplication.translate("simulatorWidget", "Prop.", None, QtGui.QApplication.UnicodeUTF8))
        self.tekComb.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Technolgie combustion", None, QtGui.QApplication.UnicodeUTF8))
        self.tekImp.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Technologie impulsion", None, QtGui.QApplication.UnicodeUTF8))
        self.lTatt.setText(QtGui.QApplication.translate("simulatorWidget", "Att.", None, QtGui.QApplication.UnicodeUTF8))
        self.tekDarmes.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Technologie armes défenseur", None, QtGui.QApplication.UnicodeUTF8))
        self.tekAarmes.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Technologie armes attaquant", None, QtGui.QApplication.UnicodeUTF8))
        self.tekDprotec.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Technologie protection défenseur", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxRess.setTitle(QtGui.QApplication.translate("simulatorWidget", "Ressources", None, QtGui.QApplication.UnicodeUTF8))
        self.ressD.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Deutérium", None, QtGui.QApplication.UnicodeUTF8))
        self.ressC.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Cristal", None, QtGui.QApplication.UnicodeUTF8))
        self.ressM.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Métal", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFret.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Nombre de vaisseaux pour pillage", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFret.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Choix du type de vaisseau", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFret.addItem(QtGui.QApplication.translate("simulatorWidget", "pt", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFret.addItem(QtGui.QApplication.translate("simulatorWidget", "gt", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFret.addItem(QtGui.QApplication.translate("simulatorWidget", "cle", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFret.addItem(QtGui.QApplication.translate("simulatorWidget", "clo", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFret.addItem(QtGui.QApplication.translate("simulatorWidget", "cr", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFret.addItem(QtGui.QApplication.translate("simulatorWidget", "vb", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFret.addItem(QtGui.QApplication.translate("simulatorWidget", "vc", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFret.addItem(QtGui.QApplication.translate("simulatorWidget", "re", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFret.addItem(QtGui.QApplication.translate("simulatorWidget", "bo", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFret.addItem(QtGui.QApplication.translate("simulatorWidget", "de", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFret.addItem(QtGui.QApplication.translate("simulatorWidget", "edlm", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFret.addItem(QtGui.QApplication.translate("simulatorWidget", "tr", None, QtGui.QApplication.UnicodeUTF8))
        self.lReSim.setText(QtGui.QApplication.translate("simulatorWidget", "Simulations :", None, QtGui.QApplication.UnicodeUTF8))
        self.lReRes.setText(QtGui.QApplication.translate("simulatorWidget", "Résultat :", None, QtGui.QApplication.UnicodeUTF8))
        self.lReTou.setText(QtGui.QApplication.translate("simulatorWidget", "tours :", None, QtGui.QApplication.UnicodeUTF8))
        self.lRePer.setText(QtGui.QApplication.translate("simulatorWidget", "Pertes :", None, QtGui.QApplication.UnicodeUTF8))
        self.lReCdrd.setText(QtGui.QApplication.translate("simulatorWidget", "Cdr :", None, QtGui.QApplication.UnicodeUTF8))
        self.lReGaid.setText(QtGui.QApplication.translate("simulatorWidget", "Gains :", None, QtGui.QApplication.UnicodeUTF8))
        self.lReButT.setText(QtGui.QApplication.translate("simulatorWidget", "Butin T. :", None, QtGui.QApplication.UnicodeUTF8))
        self.lReButR.setText(QtGui.QApplication.translate("simulatorWidget", "Butin R. :", None, QtGui.QApplication.UnicodeUTF8))
        self.lReTot.setText(QtGui.QApplication.translate("simulatorWidget", "Total :", None, QtGui.QApplication.UnicodeUTF8))
        self.lRePeD.setText(QtGui.QApplication.translate("simulatorWidget", "Pertes D. :", None, QtGui.QApplication.UnicodeUTF8))
        self.lReMin.setText(QtGui.QApplication.translate("simulatorWidget", "minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.lReGai.setText(QtGui.QApplication.translate("simulatorWidget", "Gains :", None, QtGui.QApplication.UnicodeUTF8))
        self.lReMoy.setText(QtGui.QApplication.translate("simulatorWidget", "moyenne", None, QtGui.QApplication.UnicodeUTF8))
        self.lRePeA.setText(QtGui.QApplication.translate("simulatorWidget", "Pertes A. :", None, QtGui.QApplication.UnicodeUTF8))
        self.lReMax.setText(QtGui.QApplication.translate("simulatorWidget", "maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.lReCdr.setText(QtGui.QApplication.translate("simulatorWidget", "Cdr :", None, QtGui.QApplication.UnicodeUTF8))
        self.lReRec.setText(QtGui.QApplication.translate("simulatorWidget", "Recy. :", None, QtGui.QApplication.UnicodeUTF8))
        self.results.setTabText(self.results.indexOf(self.tabResult), QtGui.QApplication.translate("simulatorWidget", "Résultat", None, QtGui.QApplication.UnicodeUTF8))
        self.histoBarSlider.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Nombres de barres", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChooseHisto.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Données à afficher", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChooseHisto.addItem(QtGui.QApplication.translate("simulatorWidget", "Gains attaquant", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChooseHisto.addItem(QtGui.QApplication.translate("simulatorWidget", "Gains défenseur", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChooseHisto.addItem(QtGui.QApplication.translate("simulatorWidget", "Pertes attaquant", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChooseHisto.addItem(QtGui.QApplication.translate("simulatorWidget", "Pertes défenseur", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChooseHisto.addItem(QtGui.QApplication.translate("simulatorWidget", "CDR", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxChooseHisto.addItem(QtGui.QApplication.translate("simulatorWidget", "Recycleurs", None, QtGui.QApplication.UnicodeUTF8))
        self.results.setTabText(self.results.indexOf(self.tabGraph), QtGui.QApplication.translate("simulatorWidget", "Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.results.setTabText(self.results.indexOf(self.tabAtt), QtGui.QApplication.translate("simulatorWidget", "Attaquant", None, QtGui.QApplication.UnicodeUTF8))
        self.results.setTabText(self.results.indexOf(self.tabDef), QtGui.QApplication.translate("simulatorWidget", "Défenseur", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxTrajet.setTitle(QtGui.QApplication.translate("simulatorWidget", "Trajet", None, QtGui.QApplication.UnicodeUTF8))
        self.lTrPo.setText(QtGui.QApplication.translate("simulatorWidget", "<b>%</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.lTrvit.setText(QtGui.QApplication.translate("simulatorWidget", "Vitesse", None, QtGui.QApplication.UnicodeUTF8))
        self.lTrCib.setText(QtGui.QApplication.translate("simulatorWidget", "Cible", None, QtGui.QApplication.UnicodeUTF8))
        self.phalLCD.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Heure locale de départ", None, QtGui.QApplication.UnicodeUTF8))
        self.timeLcd.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Durée du trajet", None, QtGui.QApplication.UnicodeUTF8))
        self.lTrDep.setText(QtGui.QApplication.translate("simulatorWidget", "Départ", None, QtGui.QApplication.UnicodeUTF8))
        self.cible.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Coordonnées de la cible sous forme x:xxx:xx", None, QtGui.QApplication.UnicodeUTF8))
        self.deutLcd.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Deuterium consomé", None, QtGui.QApplication.UnicodeUTF8))
        self.phallange.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Date/heure de l\'impact souhaité", None, QtGui.QApplication.UnicodeUTF8))
        self.phallange.setDisplayFormat(QtGui.QApplication.translate("simulatorWidget", "dd/MM/yy HH:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.depart.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Coordonnées de départ sous forme x:xxx:xx", None, QtGui.QApplication.UnicodeUTF8))
        self.copyPaste.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Collez votre rapport ici", None, QtGui.QApplication.UnicodeUTF8))
        self.simuler.setToolTip(QtGui.QApplication.translate("simulatorWidget", "Démarrer la simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.simuler.setText(QtGui.QApplication.translate("simulatorWidget", "START", None, QtGui.QApplication.UnicodeUTF8))

