pref('Xtense.autohide', false);
pref('Xtense.autostart', true);
pref('Xtense.calls-toopltip-messages', true);
pref('Xtense.context-menu', true);
pref('Xtense.debug', true);
pref('Xtense.dev', false);
pref('Xtense.display-execution-time', true);
pref('Xtense.fixpopups', true);
pref('Xtense.fresh-install', true);
pref('Xtense.handle-ally_list', true);
pref('Xtense.handle-buildings', true);
pref('Xtense.handle-defense', true);
pref('Xtense.handle-fleet', true);
pref('Xtense.handle-researchs', true);
pref('Xtense.handle-messages', true);
pref('Xtense.handle-overview', true);
pref('Xtense.handle-hostiles', true);
pref('Xtense.handle-ranking', true);
pref('Xtense.handle-resources', true);
pref('Xtense.handle-system', true);
pref('Xtense.log-display-time', false);
pref('Xtense.log-max-size', 50);
pref('Xtense.log-time-format', 1);
pref('Xtense.log-hide_psw', true);
pref('Xtense.msg-ally_msg', false);
pref('Xtense.msg-ennemy_spy', true);
pref('Xtense.msg-expeditions', true);
pref('Xtense.msg-msg', false);
pref('Xtense.msg-rc', false);
pref('Xtense.msg-rc_cdr', false);
pref('Xtense.msg-spy', true);
pref('Xtense.previous-revision', '0');
pref('Xtense.server-cache0', '({name: "", version: ""})');
pref('Xtense.server-cache1', '({name: "", version: ""})');
pref('Xtense.server-cache2', '({name: "", version: ""})');
pref('Xtense.server-cache3', '({name: "", version: ""})');
pref('Xtense.server-cache4', '({name: "", version: ""})');
pref('Xtense.server0', '');
pref('Xtense.server1', '');
pref('Xtense.server2', '');
pref('Xtense.server3', '');
pref('Xtense.server4', '');
pref('Xtense.spy-debug', false);
pref('Xtense.display-new-messages', true);
